#!/bin/bash
# export_markdown.sh — SpecFarm Drift Markdown Exporter
# Converts drift engine output to a structured Markdown report.
#
# Usage:
#   source .specfarm/src/drift/export_markdown.sh
#   export_drift_markdown <drift_output> <output_file>
#
# Or pipe mode:
#   bin/drift-engine | export_drift_markdown_stdin > reports/drift.md

EXPORT_MD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(cd "$EXPORT_MD_DIR/../.." && pwd)"

DRIFT_REPORT_DIR="${DRIFT_REPORT_DIR:-reports}"
DRIFT_REPORT_TEMPLATE="${DRIFT_REPORT_TEMPLATE:-$BASE_DIR/src/drift/templates/drift_report.md.tpl}"

# export_drift_markdown DRIFT_OUTPUT OUTPUT_FILE
# Parse drift engine tabular output and render to Markdown.
# DRIFT_OUTPUT: raw text output from run_drift_check
# OUTPUT_FILE: path to write the markdown report (or "-" for stdout)
export_markdown() {
    local drift_output="$1"
    local output_file="${2:--}"

    local timestamp
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    local scope_line total_line adherence rule_rows
    scope_line=$(echo "$drift_output" | grep "^Scope:" || echo "")
    total_line=$(echo "$drift_output" | grep "^TOTAL ADHERENCE:" || echo "TOTAL ADHERENCE: N/A")
    adherence=$(echo "$total_line" | grep -o "[0-9]\+%" || echo "N/A")

    # Parse table rows (lines with | separator, skipping header/separator)
    rule_rows=$(echo "$drift_output" | \
        grep "^[A-Z].\+|" | \
        grep -v "^Rule ID" | \
        awk -F'|' '{
            id=$1; score=$2; status=$3;
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", id);
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", score);
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", status);
            if (id != "") {
                icon = "❌";
                if (status == "PASS")       icon = "✅";
                if (status == "JUSTIFIED")  icon = "🔵";
                printf "| %-30s | %-6s | %-10s | %s |\n", id, score, status, icon;
            }
        }')

    # Read template if it exists, otherwise use inline template
    local template
    if [[ -f "$DRIFT_REPORT_TEMPLATE" ]]; then
        template=$(cat "$DRIFT_REPORT_TEMPLATE")
    else
        template='# SpecFarm Drift Report

> Generated: {{TIMESTAMP}}
{{SCOPE}}

## Summary

**Total Adherence**: {{ADHERENCE}}

## Rules

| Rule ID | Score | Status | |
|---------|-------|--------|---|
{{RULE_ROWS}}

---

*Generated by [SpecFarm](https://github.com/graphedge/specfarm)*
'
    fi

    # Substitute placeholders
    local scope_md=""
    [[ -n "$scope_line" ]] && scope_md="> ${scope_line}"

    local report
    report="${template//\{\{TIMESTAMP\}\}/$timestamp}"
    report="${report//\{\{SCOPE\}\}/$scope_md}"
    report="${report//\{\{ADHERENCE\}\}/$adherence}"
    report="${report//\{\{RULE_ROWS\}\}/$rule_rows}"

    if [[ "$output_file" == "-" ]]; then
        echo "$report"
    else
        mkdir -p "$(dirname "$output_file")"
        echo "$report" > "$output_file"
        echo "Drift report written to $output_file"
    fi
}
