# SpecFarm Drift Report

> Generated: {{TIMESTAMP}}
{{SCOPE}}

## Summary

**Total Adherence**: {{ADHERENCE}}

## Rules

| Rule ID | Score | Status | |
|---------|-------|--------|---|
{{RULE_ROWS}}

---

*Generated by [SpecFarm](https://github.com/graphedge/specfarm)*
